### ISSUE TITLE
Warn user of appointment conflicts on DS calendar

### ISSUE THREAD

**Issue by Cieramaddox** [department-of-veterans-affairs/va.gov-team#101218]
## Description
We currently block users from scheduling appointments at the same time as an existing appointment. This adds an additional check to the page where they select a date. This way the user doesn't have to run through the entire flow before being blocked from scheduling.

Note that this work is for the VistA direct schedule workflow. This will inform the future CC work (this should come first)

---

### Design Assets
- [Figma file](https://www.figma.com/design/HnExAM5SGNXzUlv9yRS87t/Working-File-%7C-Appointments-FE?node-id=2878-22083&t=GObHD9NGv381adpS-1)

## Definition of Done
- [x] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove) 

---

**Comment by JunTaoLuo** [comment]
Feature flag has been added in https://github.com/department-of-veterans-affairs/va.gov-team/issues/104288. This work is now unblocked.

**Comment by outerpress** [comment]
@vbahinwillit @JunTaoLuo before we start validation, can you confirm which users the feature flag is enabled for? Or is it on for all staging users.

FYI @department-of-veterans-affairs/uae-ux - this one will be a little bit tricky because we'll need a user with an appointment that coincides with an available time slot. If Judy doesn't have any available, you can ask Michael Shatalov in #appointments-team to set up the scenario you need.

Feel free to assign yourself to the ticket if you want to pick it up for testing.

**Comment by JunTaoLuo** [comment]
I just turned on the feature flag for every user in staging since I'm not sure which one you'd like to test with. Let me know if there are issues and I can restrict it to specific users if needed.

**Comment by outerpress** [comment]
Perfect, thanks @JunTaoLuo !

**Comment by Jenny-yw** [comment]
@JunTaoLuo  Judy doesn’t have any available, but another testing account (patient999@id.me) worked! There seems to be a time zone issue—the existing appointment is at 4 PM ET on May 5, but on the calendar, it incorrectly overlaps with 4 PM MT instead of 2 PM MT (see screenshot). Is this a bug, or just an issue with this specific testing account? 

cc @outerpress

**Comment by JunTaoLuo** [comment]
@vbahinwillit can you take a look at the timezone discrepancy since you worked on this?

**Comment by vbahinwillit** [comment]
@Jenny-yw - What are the steps to reproduce? What type of care and facility did you choose? Thanks

**Comment by Jenny-yw** [comment]
@vbahinwillit 
Amputation care > Fort Collins VA clinics > "Yes, make my appointment here" > 5/5/2025 > then you should be able to see the timezone discrepancy

**Comment by Jenny-yw** [comment]
Could we not show the unavailable time slots in the scheduling flow?

**Comment by outerpress** [comment]
> Could we not show the unavailable time slots in the scheduling flow?

@Jenny-yw I think we decided on this path so the user had visibility into why the date wasn't available, in case they needed to cancel the conflicting appointment. But check with @Cieramaddox to confirm

**Comment by Jenny-yw** [comment]
Aside from the time zone discrepancies, all criteria for the accessibility audit have been met. I will close this ticket.

**Comment by JunTaoLuo** [comment]
We're working on fixing the timezone discrepancy so I'm re-opening this ticket to make sure we don't lose track of this.

**Comment by outerpress** [comment]
@Jenny-yw for future reference, the dev who did the work should always close the ticket. Once you're done validating, you can just drop a comment for the assigned dev and leave the ticket for them to deal with :)

**Comment by Jenny-yw** [comment]
@JunTaoLuo It seems that the time slots are not showing in the calendar during scheduling flow, so I couldn't verify if the time zone discrepancy still exists. 

![Image](https://github.com/user-attachments/assets/4ed712fd-2697-4f1c-8cd0-6706db55ca95)
![Image](https://github.com/user-attachments/assets/ba8cb207-9ea8-44f8-8a76-8805962bfe65)

**Comment by JunTaoLuo** [comment]
@outerpress @simiadebowale @vbahinwillit can one of you help figure out how we can set up the correct slots and appointments to test for a potential conflict?

**Comment by Jenny-yw** [comment]
@JunTaoLuo I was able to find the a conflict in another testing account (999), and it looks like the time zone discrepancy is not fixed. 

![Image](https://github.com/user-attachments/assets/fad693c2-1c1e-4d01-b656-14dc53c4b25a)
![Image](https://github.com/user-attachments/assets/d17365e3-5564-46fb-88ae-a81d1a2e8250)

**Comment by JunTaoLuo** [comment]
@vbahinwillit can you take another look since you worked on this ticket.

**Comment by vbahinwillit** [comment]
@Jenny-yw - Ready for validation.

**Comment by Jenny-yw** [comment]
@vbahinwillit @JunTaoLuo Timezone discrepancy is fixed, and the error alert shows correctly!

**Comment by JunTaoLuo** [comment]
Deployed in https://github.com/department-of-veterans-affairs/vets-website/actions/runs/14268460285

**Comment by Jenny-yw** [comment]
@vbahinwillit Not sure if this ticket needs to be reopened, but I’ve noticed some inconsistent behavior with this feature again. It sometimes works as expected, and other times it doesn’t — though if that’s just due to the nature of testing in staging, feel free to disregard.
Additionally, another issue I consistently see is that once the alert appears, it doesn’t clear when I select a different day (see recording). Could we remove alert when users select a different date?

https://github.com/user-attachments/assets/7f19703f-0825-440c-9896-d5c8fc15a770

**Comment by outerpress** [comment]
@Jenny-yw could you file a bug ticket for the second issue? 

And do you have any more info on the first issue?

FYI @ala-yna we should turn off the flag for this one if users can't select another date/time when the validation message shows. I'll see if I can recreate it.

**Comment by JunTaoLuo** [comment]
FYI for the second issue I think I know why it's happening.

In the video, even though a different day was chosen on the calendar, no time slot was selected so the previous selection (3PM on the 6th) is the current selection. That's why the alert message still shows up. In fact, later on in the video, when the 6th is chosen on the calendar, you can see that the 3PM option is still selected (radio button filled in). 

I don't think this prevents users from selecting another time and date so I'm not sure if it's necessary to turn off the flag. I do agree that the message is confusing and ideally we should hide the alert if a different day is chosen. But I think that probably warrants a different enhancement ticket.

**Comment by JunTaoLuo** [comment]
Regarding the first issue, I'm curious if we can get a repro of the bug. 

During the demo, the existing appointment was at 2PM and the slot chosen was 3PM so that was why there was no conflict. I understand that it was working previously but I'm wondering if a different account with an existing 3PM appointment was used. It can also be the case that the appointment time was modified by someone on the backend for that particular staging user between yesterday and today. In any case, it would be nice to get a repro of the bug so we can debug into it further.

**Comment by Jenny-yw** [comment]
@JunTaoLuo Thanks for sharing your input from the technical side.

You’re right about the second issue—it doesn’t block users from selecting other dates. The alert should be hidden once a different day is selected.

As for the first issue, I don’t have additional details at the moment—just that it seems to work inconsistently. I showed it to Tony when he was working on the ticket. It was a tricky one. 

I’ll go ahead and create tickets for both issues. cc @outerpress

**Comment by JunTaoLuo** [comment]
I'll create the engineering tickets since we now understand what's going on for both of the issues mentioned.
