### ISSUE TITLE
Compare live COVID-19 vaccines at VA page with Spanish and Tagalog versions and make needed changes

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#106525]
### Issue description

We've made changes to the English [COVID-19 vaccines at VA](https://www.va.gov/health-care/covid-19-vaccine/) page in recent months and may not have made the same changes on the Spanish and Tagalog pages. We need to do a comparison of the live English page with the Spanish and Tagalog pages and make any updates needed. For the Spanish page, if there is a fair amount of content that needs to be translated, we'll send it out. If it's minimal updates, we can make those ourselves. If there are Tagalog changes, we'll need to prep a document to send out to the translation team. 

Note: We don't use the State Department for our COVID-19 translation work. Instead we'll send it to another group within VA. 

### Tasks

- [x] Assess request
- [x] If needed, prep a Spanish document to send out to translators (Juliana)
- [x] If needed, prep a Tagalog document to send out to translators (Juliana)
- [x] Update Spanish page (Juliana)
- [ ] Update Tagalog page (Juliana) 
- [x] Copyedit Spanish page
- [ ] Review Tagalog page
- [x] Publish Spanish page
- [ ] Publish Tagalog page

### Acceptance Criteria
- [x] Updated Spanish page is live on the site
- [x] Updated Tagalog page is live on the site

**Comment by juliana-jara** [comment]
Hi @RLHecht . I compared the Spanish page to the English one. The good news is that we can officially say that the Spanish equivalent is up to date with the English one. The is only one paragraph that will need to be removed (highlighted in yellow in the draft) and some minor edits that I recommend to improve the readability. I made those recommendations in the comments of the draft. I do not believe they are critical enough to involve State but it is up to you. [Here's the draft](https://dvagov.sharepoint.com/:w:/r/sites/oitcontentiateam/_layouts/15/Doc.aspx?sourcedoc=%7B22249E04-4AA8-49D3-B46B-0A86EDF3A2B1%7D&file=Spanish_Vacunas%20contra%20el%20COVID-19%20en%20VA_changes%20needed.docx&action=default&mobileredirect=true).
On another note, the Tagalog page seems to be up to date. I used the Google translate feature to see if the extra paragraph that needs to be removed from the Spanish equivalent needed to be removed for this one as well but it seems like that was done already. I scanned the document to try and identify if there were any inconsistencies but I did not see any as far as I could tell. Therefore, there is no Tagalog draft needed for the next steps of this task.

**Comment by juliana-jara** [comment]
Hi @RLHecht want to make sure you saw the latest update on this ticket. Thanks!

**Comment by RLHecht** [comment]
Sorry this got lost in my list. I just added comments to the sharepoint doc. Thanks!

**Comment by juliana-jara** [comment]
Hi @RLHecht I replied to your comments, please let me know if I can start making the changes in Drupal. Thank you!

**Comment by juliana-jara** [comment]
@RLHecht I went through your comments in the document and made the changes in Drupal. https://prod.cms.va.gov/node/16359/revisions/975782/view

I also changed the word "concertar" for "agendar" in the "Asistencia frente a una catástrofe" page. Please note that I noticed there are some broken links when doing so but did not change them because I am not sure what the process for that is: https://prod.cms.va.gov/node/73621/revisions/975787/view 

Thank you.

**Comment by RLHecht** [comment]
Thanks! I'll review the COVID page and publish.

For the disaster help page, sometimes Drupal shows false broken links. I would first click the links they're mentioning and if they are still working, just leave them. If they've been removed and the English equivalent exists, we should point there and put (en ingles) at the end of the link. If they are broken and there's no English page, we'll probably want to remove the link text altogether.

**Comment by RLHecht** [comment]
I published the Spanish page. Moving to validate and will close once it's live.

**Comment by juliana-jara** [comment]
@RLHecht Both the English and Spanish versions have the same broken links and it's those taking the user to FEMA pages. Most are false. There is however one that is an archived page but you can still see the content. I will not make any changes to them then since both English and Spanish currently have the same content.

**Comment by RLHecht** [comment]
@juliana-jara I just discovered we had some draft changes that were never published to the English COVID-19 page. that means we'l need to make the same changes on the Spanish and Tagalog pages. Once the changes are showing on the live site, can you make updates to the Spanish page? We can then send out the changes we'll need to make on the Tagalog page. Thanks!

**Comment by juliana-jara** [comment]
OK. Just let me know when the changes are live! Thanks.

**Comment by RLHecht** [comment]
they are live

**Comment by juliana-jara** [comment]
@RLHecht It looks like the CHAMPVA reference was removed from the Tagalog page already 

![Image](https://github.com/user-attachments/assets/5a021910-14c8-4830-ac75-f8bffb987de0)

**Comment by RLHecht** [comment]
Thanks! I published this change in Spanish. I'll move to validate and can close once I confirm it's live.
