### ISSUE TITLE
Users with APO AP addresses are unable to update their VA.gov mailing address

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#1135]
### Status

[UNRESOLVED, RESOLVED]

### Severity Analysis

*Estimate of how critical this bug is*

- `sev 1` 
    - Immediate resolution needed
    - Critical incident
- `sev 2` 
    - Needs a special deploy
    - Needs SME
    - Regression that went uncaught in dev/staging
- `sev 3` 
    - Can go out in a regular deploy but still needs fixed ASAP
    - Can be put into the owning team's backlog and scheduled by PM

### User Impact 

- Users with APO AP addresses (those living on "pacific" bases) are unable to update their mailing address on their VA.gov profile causing them frustration and concern that their mail is being sent to the wrong location.  

### Description

- Users with APO AP addresses have two main issues. First, the "state" drop down in the edit mailing address pop up lists Armed Forces Pacific as AE when it is supposed to be AP. This is confusing and should be updated to reflect the correct acronym. The other issue is that even when they select the Armed Forces Pacific field in the state dropdown, users are shown an error message that their address cannot be updated (see screenshot). This is slightly different from the other updating address issue because this error message is shown in the edit mailing address pop up window whereas the other example of users unable to update their mailing address, the edit address pop up disappears and the error messages are shown at the top of the profile page and by the mailing address section of the profile. 

### Steps to Reproduce

There are three examples of this issue occurring. I tested with the address for one of the users but am not sharing for PII reasons. Please let me know if you the address for your own testing. 

- Sign in to VA.gov on a identity proofed account
- Go to VA.gov profile and click "edit" next to mailing address. 
- Edit pop up window appears. Enter in new address. Enter APO for city. Select Armed Forces Pacific (AE) in state drop down.
-Click update button. 

#### Expected Results

- Users mailing address will be updated

#### Actual Results

- Page reloads but edit popup stays open. When you scroll up to the top of the edit popup, you see the attached error message. 

### Further Details
See attached spreadsheet for more examples of issues. 

- Sentry Issue Link
- ServiceNow (or other source) link
- Components, Transaction, URL
- Platform, User Agent, Browser, Version
- Screen size, viewport, zoom level
- Screenshots

### Proposed Solution

- *Summary of solution*
- *Link to related tickets*

**Comment by clantosswett** [comment]
[APO AP Address Issues.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3521552/APO.AP.Address.Issues.xlsx)
![AP Content Issue](https://user-images.githubusercontent.com/32465263/63364113-f3612a80-c342-11e9-8b09-5852e2fd485e.PNG)

**Comment by alexpappasoddball** [comment]
@Justin-Pickett I believe this one is for your team. If so can you relabel accordingly and remove the triage & triage-incident?

**Comment by Justin-Pickett** [comment]
@erikphansen @lihanli can you check this issue out.

**Comment by Justin-Pickett** [comment]
@lihanli will check into this ticket.

**Comment by lihanli** [comment]
@erikphansen  i think this is a frontend bug. the api is expecting `OVERSEAS MILITARY` for `addressType`, but the frontend is sending `OVERSEAS_MILITARY`. looks like it was accidentally changed to the wrong value in this PR https://github.com/department-of-veterans-affairs/vets-website/pull/8107/files

**Comment by erikphansen** [comment]
@clantosswett A fix for this has been merged. Is there any way that you can validate that things work in prod now?

**Comment by Justin-Pickett** [comment]
@clantosswett can you validate this is working in Production so we can close out this ticket. Thanks so much.

**Comment by erikphansen** [comment]
_bump_ @clantosswett can you validate that this bug has been resolved? Thanks!

**Comment by clantosswett** [comment]
I am so sorry for not responding to this earlier. I reached out to the users about trying to update their address but I have not heard back, which is usually a good sign. That being said, I will follow up and let you know if I hear anything. I don't have access to an account in production that would allow me to complete this task so I am going to ask around and see if someone might have the ability to test in case we don't get confirmation from the users.

**Comment by Justin-Pickett** [comment]
@clantosswett can you provide an update on this ticket if you have been able to reach out to any other team members to test this item so we can look at closing this ticket.

**Comment by clantosswett** [comment]
@Justin-Pickett I reached out yesterday to 24 users who reported experiencing this issue. So far, two users have responded to my outreach and notified me they are still experiencing the problem and are unable to update their address on VA.gov. Let me know if you want more details about the users and we can figure out the past way to share that information since it is PII.

**Comment by Rick-N-Thailand** [comment]
@clantosswett 
Sorry to hijack... Found this post while trying to find a solution to my problem with the VA.gov site.  I have not been able to find a support line to report the errors.
 
Mailing and Home address is not accepting (_We couldn't save your ...._)(####-my number is masked for this post):
JUSMAGTHAI
BOX R ####
APO AP 96546

or

UNIT 46190 BOX R ####
APO AP 96546


In addition, under Mailing Address, cannot add APT 12345, UNIT 12345, #12345 etc... without the system error "_We couldn't save your...._"

**Comment by Justin-Pickett** [comment]
@lihanli can you check into the above message from "Rick-N-Thailand". I was about to close this issue but it appears there still may be some issues users are experiencing when trying to update their address.

**Comment by Rick-N-Thailand** [comment]
Hi All,

Checked today and the error still exists:
If just the address, the system accepts.  However when I try to input the Unit #, I receive this error:
_"We couldn’t save your recent mailing address update. Please try again later."_

When I try to input my APO AP address:
_"We couldn’t save your recent home address update. Please try again later."_

Sincerely,

Rick

**Comment by erikphansen** [comment]
Was able to replicate the errors that @Rick-N-Thailand is seeing. This is a sample of the server response that we saw:
```
{
  "data": {
    "id": "",
    "type": "async_transaction_vet360_address_transactions",
    "attributes": {
      "transactionId": "7a2ba685-6dfa-470c-bb5b-99f5c8c600e4",
      "transactionStatus": "COMPLETED_FAILURE",
      "type": "AsyncTransaction::Vet360::AddressTransaction",
      "metadata": [
        {
          "code": "ADDRVAL112",
          "key": "addressBio.AddressCouldNotBeFound",
          "retryable": null,
          "severity": "ERROR",
          "text": "The Address could not be found"
        }
      ]
    }
  }
}
```
Which is basically vet360 saying that it doesn't think that's a valid address.

**Comment by erikphansen** [comment]
@Rick-N-Thailand Just wanted to let you know that we are looking into this and trying to resolve the problem

**Comment by Justin-Pickett** [comment]
@erikphansen and @lihanli any update on this ticket?

**Comment by Rick-N-Thailand** [comment]
Hi,

Will this be resolved or status please.  I am still unable to properly input my addresses into the system.

Thank you,

**Comment by Justin-Pickett** [comment]
This error will be resolved as progress is made on the address override work is completed. Closing for now. We'll revisit if this isn't fixed when the current work to correct this goes out.
