### ISSUE TITLE
Work-in-progress 508-defect-1 [COGNITION, SEMANTIC MARKUP]: Form field instructions MUST be associated with inputs or buttons 

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#16261]
# [508-defect-1 :exclamation: Launchblocker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

<hr/>

## Point of Contact

**VFS Point of Contact:** Jennifer

### Needs a legend
![Screen Shot 2020-11-16 at 5 32 06 PM](https://user-images.githubusercontent.com/57469/99317801-9fd6d880-2834-11eb-87d3-3e445e03839f.png)

### Also needs a legend
![Screen Shot 2020-11-16 at 5 33 00 PM](https://user-images.githubusercontent.com/57469/99317802-a06f6f00-2834-11eb-8192-c6c30595396a.png)

### Legend added
![Screen Shot 2020-11-16 at 5 37 09 PM](https://user-images.githubusercontent.com/57469/99317805-a06f6f00-2834-11eb-99f3-1cf1e3af52a7.png)

**Comment by Mottie** [comment]
This _should_ be fixed in https://github.com/department-of-veterans-affairs/vets-website/pull/15315

**Comment by joshkimux** [comment]
@Mottie I've updated the ticket to bring one more fieldset to your attention 🙇 
If we can handle multiple fieldsets on this page and add `aria-describedby` to the radio selections as documented in this ticket, then we shouldn't need to split this into separate pages.

**Comment by Mottie** [comment]
This ticket isn't applicable anymore, correct?

**Comment by joshkimux** [comment]
@Mottie We'll be talking about this in our meeting Friday! It is no longer a launchblocker, but I believe the representative name/phone number is still not contained in a fieldset on its own individual page which might make it a 2 or 3. I'll need to double check again once staging.va.gov is back up!

**Comment by caw310** [comment]
Discussed in 1/8 DSC meeting. 

Action Items
Add recommendation to display new page when additional inputs are going to be displayed.  Add Dos and Don’ts. 
For single field, don’t do hide, just display the input. Input not hidden (example gender)
DST to prioritize this work.

**Comment by Mottie** [comment]
This is no longer applicable to HLR.. we've moved the representative fields on to a new page

<img width="522" alt="form page showing inputs for representative first and last name, phone number, phone extension and email" src="https://user-images.githubusercontent.com/136959/157512404-19442f34-dcf6-4315-bdee-246d9af8471a.png">

**Comment by taylorkaren** [comment]
Work for this ticket, per @micahchiang :
- If we want to provide groups of fields - full name, address, etc. Then we should also provide the flexibility for engineers to properly associate fields with instructions. 
- Update 5/3/2022: We should update the full name and address fields in the new VAFSC components to optionally accept a prop that populates a fieldset legend tag.
