### ISSUE TITLE
Vet Center pages - Finalize css adjustments

### ISSUE THREAD

**Issue by brangi** [department-of-veterans-affairs/va.gov-team#22728]
After most of the sections content on Venters pages is completed. Work with Leyda to adjust css styles needed.

**Comment by lildziner** [comment]
## Please make the following styling adjustments

**H4s (Address, Phone, Located at)**
- [ ] **All breakpoints**: change to 16px, Source Sans pro, Bold (700)

**Address column**
- [ ] **1201:** change to 443px width (currently at 321px w)
- [ ] **1008**: should change to two column layout 50% width each, 8px margin on both sides of content area
- [ ] **481**: 1 column stacked layout, full width, 8px margin on both sides of content area

**Photos**
- [ ] **1201**: change to 212 px width and right-align within the 700 width content space. (Currently there’s ~100px empty space to the right)
- [ ] **1008**: should change to two column layout 50% width each, 8px margin on both sides of content area
- [ ] **481**:  tighten spacing between photo and VC name to 15px. (Currently 97px)  8px margin on both sides of content area

**Adjust spacing between each location:**
- [ ] **1201**:  40px
- [ ] **1008:** 40px
- [ ] **481:**  32px

**Comment by lildziner** [comment]
@brangi I tried to keep the issue concise, but I have screengrab references available for most of the items if you need any clarification.

**Comment by brangi** [comment]
@lildziner yes, although I am not working immediately on this. Screenshots will be really helpful.

**Comment by brangi** [comment]
@lildziner the issues on the accordions seem to be with the component itself 
<img width="1376" alt="Screen Shot 2021-04-28 at 6 00 27 PM" src="https://user-images.githubusercontent.com/100468/116483023-e69d1580-a84b-11eb-93e1-5af88a3b09b9.png">

**Comment by brangi** [comment]
In IE the header don't even render 

<img width="1343" alt="Screen Shot 2021-04-28 at 6 00 36 PM" src="https://user-images.githubusercontent.com/100468/116483035-f0267d80-a84b-11eb-80cf-68e386ddb556.png">

**Comment by brangi** [comment]
these issues are for them to fix

**Comment by brangi** [comment]
> ### Main page
> * [ ]  Map thumbnail not appearing on Edge

This is must be due to CORS, I wouldn't worry about this one now. Map will not show until they fix the CORS configs


> * [ ]  'Back to top' not appearing on IE

I can look into that one but we might have to poke who owns this component as they should be aware of it


> Visual reference
> * [ ]  Columns not stacking correctly on hours section on IE/mobile viewport sizes
> 

This is probably a valid one but really rare use case I can look at

**Comment by brangi** [comment]
fixed `Columns not stacking correctly on hours section on IE/mobile viewport sizes`
<img width="972" alt="Screen Shot 2021-04-28 at 8 53 57 PM" src="https://user-images.githubusercontent.com/100468/116493367-338ce600-a864-11eb-8735-3db982e79271.png">

**Comment by lildziner** [comment]
@brangi I updated the items above to note when they're still problematic on Chrome and also struck-thru those you pointed out that have to be fixed at the component level. I rechecked the stacking issue and I'm still seeing that one for some reason.

![image](https://user-images.githubusercontent.com/4960080/116573414-c5cfd100-a8da-11eb-99f7-040ad434cd4a.png)

**Comment by brangi** [comment]
@lildziner yeah the reason is because I have not udated the tugboat instance yet, but I will do it in my next iteration of fixes

**Comment by brangi** [comment]
Questions: What do you mean by : `Address column: change to 443px width (currently at 321px w)
(Issue observed on Windows: Chrome, Internet Explorer, Edge)`
