### ISSUE TITLE
Do address validation keys even work to override an address?

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#3216]
I don't think I understand the point of the validation key. It doesn't seem to ever work? If I enter an address that returns a single suggestion with a validation key, I can't then use that validation key to enter the address AS ORIGINALLY ENTERED.

I enter this to the validation API `POST profile/address_validation`:
```
{
  "address": {
    "address_line1": "225 irving",
    "address_line2": "unit 1",
    "address_line3": "",
    "city": "San Francisco",
    "international_postal_code": "",
    "province": "",
    "state_code": "ca",
    "zip_code": "94122",
    "zip_code_suffix": ""
  }
}
```
I get back a single suggestion from the API with a validation key of `1529453503`:

```
{
    "addresses": [
        {
            "address": {
                "address_line1": "225 Irving St Apt 1",
                "address_type": "DOMESTIC",
                "city": "San Francisco",
                "country_name": "USA",
                "country_code_iso3": "USA",
                "county_code": "06075",
                "county_name": "San Francisco",
                "state_code": "CA",
                "zip_code": "94122",
                "zip_code_suffix": "2633"
            },
            "address_meta_data": {
                "confidence_score": 98.0,
                "address_type": "Domestic",
                "delivery_point_validation": "CONFIRMED",
                "residential_delivery_indicator": "RESIDENTIAL"
            }
        }
    ],
    "validation_key": 1529453503
}
```

So pass that key to the update endpoint `PUT profile/addresses` along with the address I had originally passed to the validation endpoint:
```
{
    "id": 104273,
    "address_line1": "225 irving",
    "address_line2": "unit 1",
    "address_pou": "CORRESPONDENCE",
    "address_type": "DOMESTIC",
    "city": "San Francisco",
    "country_name": "United States",
    "state_code": "ca",
    "zip_code": "94122",
    "validation_key": 1529453503
}
```
and the transaction fails `GET profile/status/7f55bff7-7539-49f5-9ed8-08923f84b50b`:
```
{
    "data": {
        "id": "",
        "type": "async_transaction_vet360_address_transactions",
        "attributes": {
            "transaction_id": "7f55bff7-7539-49f5-9ed8-08923f84b50b",
            "transaction_status": "COMPLETED_FAILURE",
            "type": "AsyncTransaction::Vet360::AddressTransaction",
            "metadata": [
                {
                    "code": "ADDR312",
                    "key": "addressBio.failAddressOverrideCriteria",
                    "retryable": null,
                    "severity": "ERROR",
                    "text": "The address override criteria has not been met, please attempt validation again"
                }
            ]
        }
    }
}
```

If I instead make the call to `PUT profile/addresses` without sending the validation key, the update works, but behind the scene the address is "corrected" to the address that came back from the suggestion API.

This effectively makes it impossible for a user to have their address formatted as they desired, so there's not reason to even give them the option to use the address as entered.

I'm not sure if this is intended behavior with the validation API, or a bug in either the Vets API wrapper or the Vet360 APIs.

## Tasks 

Update address validation service to send addressPOU field in API calls.

## Acceptance Criteria 

Address override key should work with addresses that don't return an error.

**Comment by erikphansen** [comment]
I made another attempt at getting the validation keys to work with no luck. I noticed in the above example there was no `country_name` included with the initial call to the validation endpoint but we do send it with the call to save/update the address. So in the above example I'd actually expect the override to fail because my understanding is that the validation key needs to accompany _the same address data that generated the key in the first place._

So this was my second attempt to get an override key to work. I'm pretty sure the data used to get the validation key is identical to the data sent to the save/update endpoint. But maybe the vets-api layer is somehow "breaking" things? ¯\_(ツ)_/¯

0. Sign in as user 37
1. I call the validation endpoint:
```
POST https://staging-api.va.gov/v0/profile/address_validation

{
  "address": {
    "address_line1": "225 irving st #1",
    "city": "sf",
    "address_pou": "CORRESPONDENCE",
    "address_type": "DOMESTIC",
    "country_name": "United States",
    "state_code": "CA",
    "zip_code": "94122"
  }
}
```
2. I get back a single "corrected" address suggestion and a validation key:
```
{
  "addresses": [
    {
      "address": {
        "address_line1": "225 Irving St Apt 1",
        "address_type": "DOMESTIC",
        "city": "San Francisco",
        "country_name": "USA",
        "country_code_iso3": "USA",
        "county_code": "06075",
        "county_name": "San Francisco",
        "state_code": "CA",
        "zip_code": "94122",
        "zip_code_suffix": "2633"
      },
      "address_meta_data": {
        "confidence_score": 95.0,
        "address_type": "Domestic",
        "delivery_point_validation": "CONFIRMED",
        "residential_delivery_indicator": "RESIDENTIAL"
      }
    }
  ],
  "validation_key": 1781868460
}
```
3. I send the address from Step 1 + the validation key to the update endpoint:
```
PUT https://staging-api.va.gov/v0/profile/addresses

{
    "id": 104273,
    "address_line1": "225 irving st #1",
    "address_type": "DOMESTIC",
    "city": "sf",
    "country_name": "United States",
    "state_code": "CA",
    "zip_code": "94122",
    "address_pou": "CORRESPONDENCE",
    "validation_key": 1781868460
}
```
4. I get back a response that includes a transaction id:
```
{
  "data": {
    "id": "",
    "type": "async_transaction_vet360_address_transactions",
    "attributes": {
      "transaction_id": "6103a1f9-b64f-4f4a-ba70-560c4dcd2f5b",
      "transaction_status": "RECEIVED",
      "type": "AsyncTransaction::Vet360::AddressTransaction",
      "metadata": []
    }
  }
}
```
5. I check on the transaction by calling `GET https://staging-api.va.gov/v0//profile/status/6103a1f9-b64f-4f4a-ba70-560c4dcd2f5b`
6. I get back a failure due to override criteria not being met:
```
{
  "data": {
    "id": "",
    "type": "async_transaction_vet360_address_transactions",
    "attributes": {
      "transaction_id": "6103a1f9-b64f-4f4a-ba70-560c4dcd2f5b",
      "transaction_status": "COMPLETED_FAILURE",
      "type": "AsyncTransaction::Vet360::AddressTransaction",
      "metadata": [
        {
          "code": "ADDR312",
          "key": "addressBio.failAddressOverrideCriteria",
          "retryable": null,
          "severity": "ERROR",
          "text": "The address override criteria has not been met, please attempt validation again"
        }
      ]
    }
  }
}
```

So I think that next steps would be to see what data Vets API is actually passing to Vet360, in particular with the `PUT https://staging-api.va.gov/v0/profile/addresses` in step 3, to make sure that the address data sent to Vet360 matches the address data sent with the original validation attempt in step 1.

**Comment by lihanli** [comment]
address override should work now for this address
```json
{
  "addressLine1": "225 irving",
  "addressLine2": "unit 1",
  "city": "San Francisco",
  "requestCountry": {
    "countryCode": "USA"
  },
  "addressPOU": "CORRESPONDENCE",
  "stateProvince": {
    "code": "CA"
  },
  "zipCode5": "94122"
}
```

**Comment by Justin-Pickett** [comment]
@lihanli can we close this ticket?

**Comment by lihanli** [comment]
@erikphansen are you still getting any errors?

**Comment by erikphansen** [comment]
I'm still not able to get overrides to work for the 225 irving st address. @lihanli I don't recognize this object format:

```json
{
  "addressLine1": "225 irving",
  "addressLine2": "unit 1",
  "city": "San Francisco",
  "requestCountry": {
    "countryCode": "USA"
  },
  "addressPOU": "CORRESPONDENCE",
  "stateProvince": {
    "code": "CA"
  },
  "zipCode5": "94122"
}
```

Which endpoint are you sending that to?

**Comment by lihanli** [comment]
that is the request i sent to the vet360 api, i figured out what the problem is i'll make a PR later to fix it

**Comment by Justin-Pickett** [comment]
@lihanli lets make this an actionable ticket to deliver for sprint 10. I can create the ticket and will need your help to groom the ticket for the info that is needed in from a dev perspective. Thanks.

**Comment by Justin-Pickett** [comment]
Currently working with other teams through slack to dig into the issue. Will follow up with Lihan on status in next couple of days for any updates

**Comment by lihanli** [comment]
overriding address works for me for vets.gov.user+130@gmail.com

```javascript
let body = {
  "id": 107667,
  "address_line1": "225 irving",
  "address_line2": "unit 1",
  "address_type": "DOMESTIC",
  "country_name": "United States",
  "city": "San Francisco",
  "country_code_iso3": "USA",
  "state_code": "CA",
  "zip_code": "94122",
  "address_pou": "CORRESPONDENCE"
}

fetch(
  "https://staging-api.va.gov/v0/profile/address_validation",
  {
    "method":"POST",
    mode: 'cors',
    credentials: 'include',
    headers: {
      "content-type":"application/json"
    },
    body: JSON.stringify({ address: body })
  }
).then((data) => {
  return data.json();
}).then((data) => {
  body.validation_key = data.validation_key

  fetch(
    "https://staging-api.va.gov/v0/profile/addresses",
    {
      "method":"PUT",
      mode: 'cors',
      credentials: 'include',
      headers: {
        "content-type":"application/json"
      },
      body: JSON.stringify(body)
    }
  ).then((data) => {
    return data.json();
  }).then((data) => {
    console.log(data)
  });
});
```
