### ISSUE TITLE
Staging:  VAOS Display of Appts Slots For Direct Scheduling Showing Wrong Slots/Wrong Times/Wrong Day

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#38116]
## What happened?

1. Log in as judy.morrison@id.me.  Select Primary Care, Select VA Medical Center, Select Cheyenne. Select Green Team Clinic1.  
2. Enter desired date for appointment.  Select continue
3. Validate slots displayed in VAOS correspond to the slots shown in the response body.  See response body for this endpoint:  https://staging-api.va.gov/vaos/v2/locations/983/clinics/308/slots?start=2022-03-01T00:00:00-07:00&end=2022-04-30T00:00:00-06:00. 
4.  Compare the data in response body to the displays of actual slots in VAOS.  
5. Expected response:  Data in response body is what is seen in VAOS display of open appointment slots.  
6.  Actual response:  Data in response body is NOT what is seen in VAOS display of open appointment slots. 

See attached screen shots.  

## Specs:
Chrome
![ClinicSlotIssue_2.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/51f71098-a007-4566-b6a7-f71c0202489d)

![ClinicSlotIssue_3.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/554b1f3e-b5d3-4d01-8c48-a3661297b1bb)

**Comment by vbahinwillit** [comment]
This is may have been fixed by #36488. Please retest to verify. Thanks

**Comment by marcynadeau** [comment]
@vbahinwillit @ldelacosta There are still issues with this. I can demo on the scrum today.

**Comment by marcynadeau** [comment]
@ldelacosta @vbahinwillit Screen shots of Green Team Clinic1.  
![ClinicSlotIssue_5](https://user-images.githubusercontent.com/62026291/157710532-7e74ca04-89e4-4c81-8de8-9fc8fec6ec87.png)

**Comment by ldelacosta** [comment]
Issue is still happening. Moving back the ticket to In Progress.

**Comment by marcynadeau** [comment]
@ldelacosta @vbahinwillit Tested and passed. You can close this ticket.  
![GitHub38116_VAOSDisplayofSlots](https://user-images.githubusercontent.com/62026291/161800803-91531dfd-c1d2-47d2-82dc-82b04af545fc.png)
