### ISSUE TITLE
Publish regional processing offices page

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#78582]
## Description
First, we need to publish a new resources and support page to migrate this legacy page:

- [Regional Processing Offices](https://www.benefits.va.gov/gibill/regional_processing.asp)

Then, we need to replace the link to the legacy page with the link to the new resources and support page on these modern pages:

- [Change your GI Bill school or program](https://www.va.gov/education/change-gi-bill-benefits/)
- [How to apply for the GI Bill and related benefits](https://www.va.gov/education/how-to-apply/)

And, we need to replace the processing offices content with the link to the new resources and support page on these modern pages:

- [Foreign programs](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/study-at-foreign-schools/)
- [Verify school enrollment for DEA benefits](https://www.va.gov/resources/verify-school-enrollment-for-dea-benefits/)

### Step 1: Publish
- [x] DB: Draft a new resources and support page
- [x] AP: Review
- [x] AP: Share with BP
- [x] BP: Review
- [x] DB: Share with stakeholders
- [x] MZ, ST: Copyedit and publish

### Step 2: Redirect
- [x] DB: Work with IA to open a redirect ticket

Redirect this legacy URL:

- www.benefits.va.gov/gibill/regional_processing.asp

To the new resources and support page URL.

### Step 3: Update
- [x] DB: Replace the link to the legacy page with the link to the new resources and support page on the two modern pages above
- [x] DB: Replace the processing offices content with the link to the new resources and support page on the two modern pages above
- [x] AP: Review all four pages
- [x] MZ, ST: Copyedit and publish all four pages

## Criteria
- [x] New resources and support page is published
- [ ] IA opened a redirect ticket for the legacy URL
- [x] All four modern pages linked above are updated and published

**Comment by d-beyer** [comment]
@aprocik1 I've drafted the new [regional claims processing offices R&S page](prod.cms.va.gov/resources/gi-bill-regional-claims-processing-offices).

Two notes:
- I was unsure what the best title for this page would be. Very open to alternatives.
- I kept the formatting pretty similar to the [Verify school enrollment for DEA page](https://www.va.gov/resources/verify-school-enrollment-for-dea-benefits/) since that was made within the last year and it was pretty clean. Open to other ideas.

**Comment by aprocik1** [comment]
@d-beyer, thanks! Here are some small edits I made:

- I updated the intro (I changed "VA" to "we" and used numerals)
- I changed the question from plural to singular ("claims" became "claim")
- I added the summary below the "about GI Bill benefits" link (I used the same summary that's on the [VA education and training benefits](https://www.va.gov/education/) page)

One question: How does someone know where to mail their form? The page references both the location of their school and the state they live in. I'm assuming you copied that language from the [Verify school enrollment for DEA benefits](https://www.va.gov/resources/verify-school-enrollment-for-dea-benefits/) page. Do you know the answer to this question? If not, can you follow up with stakeholders to ask about it?

After we clarify that information, we can share this page with Beth to review. Then we can share it with stakeholders.

**Comment by d-beyer** [comment]
@aprocik1 Tammy got back to us with the correct answer (where the school is) and I've updated the Drupal page to reflect that.

**Comment by aprocik1** [comment]
Update: I shared this page with Beth via Slack.

**Comment by d-beyer** [comment]
Update: Tammy sent us more feedback on the Drupal page. I incorporated that feedback, then we ran it by Beth on 4/18, who approved it.

**Comment by d-beyer** [comment]
@aprocik1 I updated the link and text on the four pages that reference the regional processing offices:
- [Change your GI Bill school or program](http://preview-prod.vfs.va.gov/preview?nodeId=939)
- [How to apply for the GI Bill and related benefits](http://preview-prod.vfs.va.gov/preview?nodeId=943)
- [Foreign programs](http://preview-prod.vfs.va.gov/preview?nodeId=925)
- [Verify school enrollment for DEA benefits](http://preview-prod.vfs.va.gov/preview?nodeId=53598)

**Comment by aprocik1** [comment]
@d-beyer, thanks! I noticed that these pages include content about and links to the [Find VA locations page](https://www.va.gov/find-locations/). That content reads like this:

> [Header] In person
> Go to a VA regional office and ask a staff member to help you.
> 
> [Link] Find a VA regional office near you

I don't want to cause confusion with similar content and links to our new page, so I updated your content to this:

> [Header] By mail
> Fill out your form and mail it to the VA regional processing office that's right for you.
> 
> [Link] Find your regional processing office address

Let me know if you any concerns about this. If not, you can share the new page and these 4 updated pages with Megan for copyediting and publishing.

**Comment by d-beyer** [comment]
Hi @megzehn -- We've got one small new R&S page to publish, and we've updated texts and links on four other pages to refer to it.

**New R&S page:** [Regional processing office addresses for GI Bill claims](http://preview-prod.vfs.va.gov/preview?nodeId=67024)

**Pages with updated references/links:**
[Change your GI Bill school or program](http://preview-prod.vfs.va.gov/preview?nodeId=939)
[How to apply for the GI Bill and related benefits](http://preview-prod.vfs.va.gov/preview?nodeId=943)
[Foreign programs](http://preview-prod.vfs.va.gov/preview?nodeId=925)
[Verify school enrollment for DEA benefits](http://preview-prod.vfs.va.gov/preview?nodeId=53598)

**Comment by d-beyer** [comment]
@megzehn We found three more instances of links/references to the legacy page, so we updated those as well:
- [How do I report mitigating circumstances?](https://prod.cms.va.gov/node/33831/latest)
- [Get paid back for test fees](http://preview-prod.vfs.va.gov/preview?nodeId=926)
- [Work study](http://preview-prod.vfs.va.gov/preview?nodeId=931)

**Comment by megzehn** [comment]
Thanks for this page, @d-beyer !! 

I took a first pass and asked you some questions in Slack that I'll add here:

- Do we need regional processing officer in the H1? (Just wondering if we could go with something like, "Where to mail your GI Bill application"

- Do we want to refer to someone's "GI Bill claim"? Or should we be using "GI Bill application"? I'm not sure if you've already had conversations about that, but I just want to make sure we're consistent.

**Comment by d-beyer** [comment]
Beth gave us some feedback on the order of the information for each address section. We brought this to the content team and tweaked it. Beth then gave us her approval and said we could proceed.

Also, we landed on "application" over "claim". This will be changed in copyedit.

@megzehn This is ready for you again!

**Comment by megzehn** [comment]
Thanks @d-beyer! Update: I've published the new R&S page and I'll check off these other pages as I update them. 

- [ ] [Change your GI Bill school or program](http://preview-prod.vfs.va.gov/preview?nodeId=939)
- [ ] [How to apply for the GI Bill and related benefits](http://preview-prod.vfs.va.gov/preview?nodeId=943)
- [ ] [Foreign programs](http://preview-prod.vfs.va.gov/preview?nodeId=925)
- [ ] [Verify school enrollment for DEA benefits](http://preview-prod.vfs.va.gov/preview?nodeId=53598)
- [ ] [How do I report mitigating circumstances?](https://prod.cms.va.gov/node/33831/latest)
- [ ] [Get paid back for test fees](http://preview-prod.vfs.va.gov/preview?nodeId=926)
- [ ] [Work study](http://preview-prod.vfs.va.gov/preview?nodeId=931)

**Comment by megzehn** [comment]
Update: The first 4 have been published, but I'm holding temporarily on the last 3. Noting the status and some questions here:

- [How do I report mitigating circumstances?](https://prod.cms.va.gov/node/33831/latest) -- holding because there are other edits in draft

- [Get paid back for test fees](http://preview-prod.vfs.va.gov/preview?nodeId=926) -- there are 2 links that are throwing system errors. I connected with @d-beyer and @bethpotts to figure out how to address those 
- https://inquiry.vba.va.gov/weamspub/buildSearchCountryLCCriteria.do
- https://inquiry.vba.va.gov/weamspub/buildSearchNE.do

- [Work study](http://preview-prod.vfs.va.gov/preview?nodeId=931) -- the PDF we link to on this page just mentions the Muskogee regional office and it doesn't say anything about Buffalo. Do we know why? 

CC @bethpotts and @d-beyer

**Comment by d-beyer** [comment]
Hi @bethpotts -- follow-up questions about the points @megzehn raised:
- [Get paid back for test fees](http://preview-prod.vfs.va.gov/preview?nodeId=926) -- Are these two links going to a deprecated tool? Can we just update these to point to the GI Bill Comparison Tool?
- [Work study](http://preview-prod.vfs.va.gov/preview?nodeId=931) -- 
  1. According to the date listed in the PDF, it has "expired". Do we need to do something about "expired" PDFs?
  2. Since the live page already refers to the two regional processing centers, updating the link to point to our new R&S page wouldn't change the current meaning. Can we move forward with that change?

**Comment by megzehn** [comment]
@d-beyer, for [Get paid back for test fees](http://preview-prod.vfs.va.gov/preview?nodeId=926), I had the same question. But I'm not sure we can point to the GI Bill Comparison Tool there. I'm not seeing a way to search for tests and certifications on the GBCT tool. (And we'd also need to adjust the instruction text above the link.)

In this [thread](https://dsva.slack.com/archives/C03MP8MEPCN/p1717526678017709?thread_ts=1716485465.986719&cid=C03MP8MEPCN) (which I should have tagged you on @d-beyer, sorry!) Beth said that she's going to ask Tammy to move the banner link to GBCT to under the search boxes to keep people on the page. @bethpotts , just to confirm, is it true that people can't find test fees on the GBCT tool, or do we still need to check that with the stakeholders? 

In the meantime, I think it's safe to move forward with publishing the updated regional processing link, since that's a separate issue. But let me know if you have any objections, Beth!

**Comment by bethpottsVADEPO** [comment]
- We have to point to WEAMS for licensing and cert. ([Get paid back for test fees](http://preview-prod.vfs.va.gov/preview?nodeId=926)). They are working to get that info into the GIBCT, but for now it's WEAMS. Those links are working for me. Are they still throwing errors for either of you?
- For work study, it's correct that only Muskogee processes those applications (so the PDF is correct). This means we need to adjust the language we have about this on our work study page. @megzehn I'll do that now and you can do a final copyedit and publish.
- For [How do I report mitigating circumstances?](https://prod.cms.va.gov/node/33831/latest), there don't seem to be any outstanding edits now in draft.

**Comment by megzehn** [comment]
Thanks for confirming @bethpottsVADEPO!

I just did a final review and published [Get paid back for test fees](http://preview-prod.vfs.va.gov/preview?nodeId=926). 

And that sounds good for the work study one.

**Comment by bethpottsVADEPO** [comment]
@megzehn In a convo with SMEs just now, I learned that there will be more extensive changes needed to the work study page. So for now, go ahead and publish after your final copy edit of changes sitting in draft for this page. Then in the course of our accuracy audit, we'll make any other edits needed. After you publish work study, I think that'll wrap up this ticket, yes?

**Comment by aprocik1** [comment]
I think we need to publish the work study page and implement this redirect:
- Legacy URL: www.benefits.va.gov/gibill/regional_processing.asp
- Modern URL: www.va.gov/resources/regional-processing-office-addresses-for-gi-bill-applications/

**Comment by megzehn** [comment]
Thank you @aprocik1! Confirming that I published the work study page with just the updated link. I left all the other copy the same as what is currently live. And I added a note in the revision log that we'll revisit this page during the audit. 

@d-beyer, I think this is ready for you and IA and open a redirect ticket? (Or correct me if I'm wrong, @aprocik1!)

**Comment by aprocik1** [comment]
Update: Derek confirmed with Jenny that this redirect has been requested. I'm closing this ticket as complete.
