### ISSUE TITLE
[FE] Add Spanish Translations

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#90922]
## New Content 
[NewSpanishContent.json](https://github.com/user-attachments/files/16662007/NewSpanishContent.json)

## Tasks
- [x] Add translated content to the appropriate json file
- [x] Generate error screenshots in Spanish for workflow documents to submit to the State Department

**Comment by brianseek** [comment]
of the new translations, these were no longer in the application:
```
        "expiration-date": "Fecha de vencimiento:",
        "for-in-person-appointments-you-can-still-check-in-with-your-phone-once-you-arrive-at-your-appointment": "Para las citas en persona, podrá registrarse con su teléfono una vez llegue a su cita.",
        "for-telephone-appointments-your-provider-will-call-you-you-may-need-to-wait-about-15-minutes-for-their-call-thanks-for-your-patience": "Para las citas telefónicas, su proveedor le llamará. Es posible que tenga que esperar unos 15 minutos por la llamada. Agradecemos su paciencia.",
        "if-your-appointment-is-in-person-a-staff-member-will-help-you-on-the-day-of-your-appointment": "Si su cita es en persona, un miembro del personal le asistirá el día de su cita.",
        "this-claim-is-for-your-appointment": "Esta reclamación es por su",
        "well-come-get-you-from-the-waiting-room": "Vendremos a buscarle a la sala de espera cuando sea la hora de empezar su cita. Si espera más de 15 minutos, avise a un miembro del personal.",
        "you-can-still-check-in-with-your-phone-once-you-arrive-at-your-appointment": "Aún así, podrá registrarse con su teléfono una vez llegue a su cita.",
```
These are part of the DS but seem to be in already:
```
        "day": "Día",
        "month": "Mes",
        "year": "Año",
        "please-enter-your-day-of-birth": "Ingrese su día de nacimiento",
        "please-enter-your-month-and-day-of-birth.": "Ingrese su mes y día de nacimiento.",
        "please-enter-your-month-of-birth.": "Ingrese su mes de nacimiento.",
        "please-enter-your-year-of-birth.": "Ingrese su año de nacimiento.",
```
These I'm not sure we should translate since the toggle should hard code the native language
```
        "spanish": "Español",
        "tagalog": "Tagalo",
```

Everything else should be added. Screenshots to come.

**Comment by brianseek** [comment]
pre-check-in screenshots: [pre-check-in-spanish.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODJFQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--030b263abe2b65bef37847e9aa2669baf7bdf14c/pre-check-in-spanish.zip)
day-of screenshots: [day-of-check-in-spanish.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODZFQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d1f0b4498f07a79fe8554e3a35f7386737fd89e/day-of-check-in-spanish.zip)

**Comment by brianseek** [comment]
travel: [travel-app-spanish.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUdFQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4742b1f8de11ecef2fd23b5b76c7c0d76d7aefc/travel-app-spanish.zip)

**Comment by loripusey** [comment]
@brianseek Noticed that on the new landing page for day-of that "appointment/appointments" was not translated to "cita/citas"

![image](https://github.com/user-attachments/assets/360891e8-1be9-436f-be0f-973ad8136789)

**Comment by loripusey** [comment]
@brianseek Noticied that "Video Appointment" and "Phone Appointment" are not translated.
![image](https://github.com/user-attachments/assets/e4aabefc-0590-46c5-b15a-7e67e988d5df)

**Comment by loripusey** [comment]
@brianseek Question: Did this content change from when I sent it to the State Department a few weeks ago?

What I sent off to get translated:
![image](https://github.com/user-attachments/assets/d3564163-ac3f-4aba-b6ba-21b5fb069869)

Screen shot now:
![image](https://github.com/user-attachments/assets/4cf0b132-1d2e-43b0-b012-398c20bf1e44)

**Comment by loripusey** [comment]
@brianseek Can I get a spanish screenshot of the details page after the Veteran has checked in?

**Comment by loripusey** [comment]
@brianseek I can't find screenshots for these in the zip files; perhaps I'm blind (these are for travel only) 
![image](https://github.com/user-attachments/assets/c4b88190-b3d1-4707-9cd2-2843852e0f0a)

**Comment by brianseek** [comment]
I fixed the `Appointments` translation for new landing page. I fixed the translation for `Video appointment` but we don't have a translation for `Phone appointment` we do have `Phone appointments`. Yes that content probably change, lots of content around upcoming appointments has been shifting pretty often.

Working on a new set of screenshots now, including the missing pages requested.

**Comment by brianseek** [comment]
@loripusey I needed to make some tweaks and I found a bug in the translations, but I finally got all the screens. Let me know if anything is missing from this.
[spanish.zip](https://github.com/user-attachments/files/16753580/spanish.zip)

**Comment by loripusey** [comment]
We have "phone appointments" translated; I would go ahead and infer that "phone appointment" is "Cita por teléfono" and make the change and we can see if they agree or not on the QA.

![image](https://github.com/user-attachments/assets/0daec139-cad0-49ee-a6a9-7c3006fff32d)

**Comment by loripusey** [comment]
I still don't see a screen shot for the appt details page AFTER they have completed Pre-Check-in; there should be some content about how to check in on the day of the appointment 
![image](https://github.com/user-attachments/assets/d1f0d2d8-92e3-4ec1-9e30-9cab71d782f5)

**Comment by brianseek** [comment]
@loripusey ah okay, I made a screenshot for day-of details after complete. Will make one for pre-check-in too and create that phone appointments translation

**Comment by brianseek** [comment]
@loripusey here are the updated screenshots 
[spanish-2.zip](https://github.com/user-attachments/files/16765291/spanish-2.zip)

**Comment by loripusey** [comment]
This translation is slightly different than what we have:

> 62.	"sorry-we-cant-file-now": "Lo sentimos. Ahora no podemos presentar una reclamación de reembolso de viaje para usted. Pero aún puede presentarla dentro de los <0>30 días</0> siguientes a la cita.",

![image](https://github.com/user-attachments/assets/6a050971-bc59-435a-be21-b21241814aca)

**Comment by brianseek** [comment]
That is a different message. The translation key `sorry-we-cant-file-now` is for when there is an api-error and the image is the message when a claim is ineligible. Its key is `travel-pay-cant-file-message`

**Comment by loripusey** [comment]
ugh! can you tell me the name of the file that has the message I'm looking for?

**Comment by loripusey** [comment]
nm I found it

**Comment by loripusey** [comment]
I think we're done
- We should be good to merge @brianseek 
- QA screenshots were sent to Randi on 8/27; 
    - [Q2 2024 - Spanish_2024-08-27_16-44-03.pdf](https://github.com/user-attachments/files/16766139/Q2.2024.-.Spanish_2024-08-27_16-44-03.pdf)

**Comment by brianseek** [comment]
nice work @loripusey! Will get it merged up as soon as @wullaski gives it another look

**Comment by brianseek** [comment]
merged and closing
